name: SymDPO
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.12
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - cairo=1.18.0
  - expat=2.6.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freetype=2.12.1
  - giflib=5.2.2
  - graphite2=1.3.14
  - harfbuzz=9.0.0
  - icu=75.1
  - keyutils=1.6.1
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.38
  - lerc=4.0.0
  - libcups=2.3.3
  - libdeflate=1.21
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libglib=2.80.3
  - libgomp=14.1.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.3
  - libnsl=2.0.1
  - libpng=1.6.43
  - libsqlite=3.46.1
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libtiff=4.6.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openjdk=22.0.1
  - openssl=3.3.2
  - pcre2=10.44
  - pip=24.2
  - pixman=0.43.2
  - pthread-stubs=0.3
  - python=3.9.19
  - readline=8.2
  - setuptools=72.1.0
  - tk=8.6.13
  - wheel=0.43.0
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.0
  - xorg-libxtst=1.2.5
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.6
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - accelerate==0.34.2
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - astroid==3.2.4
      - async-timeout==4.0.3
      - attrs==24.2.0
      - black==24.8.0
      - braceexpand==0.1.7
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cmake==3.30.3
      - contourpy==1.3.0
      - cycler==0.12.1
      - dataclasses==0.6
      - datasets==2.16.1
      - dill==0.3.7
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - einops==0.8.0
      - einops-exts==0.0.4
      - eval-type-backport==0.2.0
      - exceptiongroup==1.2.2
      - filelock==3.16.0
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fsspec==2023.10.0
      - ftfy==6.2.3
      - gitdb==4.0.11
      - gitpython==3.1.43
      - huggingface-hub==0.24.7
      - idna==3.8
      - importlib-resources==6.4.5
      - inflection==0.5.1
      - iniconfig==2.0.0
      - isort==5.13.2
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonlines==4.0.0
      - kiwisolver==1.4.7
      - lit==18.1.8
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.15
      - mypy==1.11.2
      - mypy-extensions==1.0.0
      - networkx==3.2.1
      - nltk==3.9.1
      - numpy==1.26.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - open-clip-torch==2.26.1
      - packaging==24.1
      - pandas==2.2.2
      - pathspec==0.12.1
      - pillow==10.4.0
      - platformdirs==4.3.2
      - pluggy==1.5.0
      - protobuf==5.28.1
      - psutil==6.0.0
      - pyarrow==17.0.0
      - pyarrow-hotfix==0.6
      - pycocoevalcap==1.2
      - pycocotools==2.0.8
      - pygments==2.18.0
      - pylint==3.2.7
      - pyparsing==3.1.4
      - pytest==8.3.3
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - regex==2024.9.11
      - requests==2.32.3
      - rich==13.8.1
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.13.1
      - sentencepiece==0.2.0
      - sentry-sdk==2.14.0
      - setproctitle==1.3.3
      - shtab==1.7.1
      - six==1.16.0
      - smmap==5.0.1
      - sympy==1.13.2
      - threadpoolctl==3.5.0
      - tiktoken==0.8.0
      - timm==1.0.9
      - tokenizers==0.19.1
      - tomli==2.0.1
      - tomlkit==0.13.2
      - torch==2.0.1
      - torchvision==0.15.2
      - tqdm==4.66.5
      - transformers==4.44.2
      - triton==2.0.0
      - typing-extensions==4.12.2
      - tyro==0.8.10
      - tzdata==2024.1
      - urllib3==2.2.2
      - wandb==0.18.0
      - wcwidth==0.2.13
      - webdataset==0.2.100
      - xxhash==3.5.0
      - yarl==1.11.1
      - zipp==3.20.1